### ISSUE TITLE
cron job creating high load

### ISSUE THREAD

**Issue by Killer1337** [owncloud/search_lucene#64]
since upgrading to owncloud 8 I am getting a lot of emails that another cron job is still running and a new one can't be started.

At first I thought there was something wrong with the news app, since that was the only one I had in mind using the cron job to fetch new feeds. The issue is discussed here: https://github.com/owncloud/core/issues/3221

But just now I received this email from cron:

    PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/www/owncloud/apps/search_lucene/3rdparty/zendframework/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php on line 85

Please let me know if you want me to provide more info if you decide to look into this.

**Comment by karlitschek** [comment]
This should be fixed in 8.0.1 Thanks for reporting this.

**Comment by DeepDiver1975** [comment]
> This should be fixed in 8.0.1 Thanks for reporting this.

not really - the execution timeout was fixed for console commands - not for cron

I'll open up a ticket in core - THX

**Comment by DeepDiver1975** [comment]
@butonic it might still be interesting to find out why that execution takes that long and if we might better break up some things into smaller pieces

**Comment by BenjaminXiao** [comment]
I am still getting this issue on 8.0.2.

Maximum execution time of 3600 seconds exceeded in /var/www/owncloud/apps/search_lucene/3rdparty/zendframework/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php on line 85

This is using the system cron job

**Comment by BenjaminXiao** [comment]
I disabled the Search Lucene plugin and it seems to have fixed the issue.

**Comment by GMTA** [comment]
I am also experiencing cron hangs with Lucene search enabled. After disabling the search app, the cron hang disappears. No new Lucene entries appear in the log file when the process hangs with 100% CPU so it seems there is something wrong in the indexing process. This does not appear to be related to the lock file issue.

**Comment by arm2arm** [comment]
same here, when user has more than 10000 files it fails.After disabling full text search app everything is ok.
